FROM node:10-slim
RUN  apt-get update &&  apt-get install -y build-essential python
WORKDIR /build
COPY package.json /build
RUN npm install
COPY . /build
RUN npm run build
#VOLUME /build

USER node
CMD ["node","dist/worker/index.js"]
