# types of ammo.
enum ItemType {
  ammo # collection the following
  centerfire
  rimfire
  shotgun

  reloading # collection of the following
  powder
  shot
  case
  primer
}
# provinces  (and territories) of canada
enum Province {
  AB
  BC
  MB
  NB
  NL
  NS
  NT
  NU
  ON
  PE
  QC
  SK
  YT
}
enum State {
  IA
  NV
}

union Region = Province | State
# colunm sort order
enum SortOrder {
  ASC
  DES
}
# column to sort on
enum SortField {
  name
  link
  # old table filters
  minPrice
  minUnitCost
}

enum FlatSortField {
  name
  link
  price
  unitCost
}

type ItemListing {
  img: String
  price: Float!
  name: String!
  link: String!
  vendor: String!
  provinces: [Region] #[Province!]!
  subType: String #!
  brand: String!
  count: Float
  unitCost: Float
  itemType: ItemType!
  ttl: Float
}
type ItemGroup {
  name: String!
  brand: String!
  subType: String #!
  itemType: ItemType!
  minPrice: Float!
  maxPrice: Float!
  minUnitCost: Float
  maxUnitCost: Float
  img: String
  vendors: [ItemListing!]!
}
type ItemListings {
  page: Int!
  pages: Int!
  pageSize: Int!
  items: [ItemGroup!]!
}

type ItemFlatListings {
  page: Int!
  pages: Int!
  pageSize: Int!
  items: [ItemListing!]!
}

type Vendor {
  name: String!
  provinces: [Region!]!
  location: String!
  logo: String!
  link: String!
  background: Boolean
  hasReloadingItems: Boolean
}
type BestPrice {
  unitCost: Float!
  calibre: String!
  type: ItemType!
}
# The "Query" type is the root of all GraphQL queries.
# (A "Mutation" type will be covered later on.)
type Query {
  vendors(province: Region): [Vendor]
  bestPrices(type: ItemType, calibres: [String!]): [BestPrice]
  itemsListings(
    page: Int
    pageSize: Int
    itemType: ItemType
    subType: String
    province: Region
    vendor: String
    sortOrder: SortOrder
    sortField: SortField
    query: String
    brand: String
  ): ItemListings

  itemsFlatListings(
    page: Int
    pageSize: Int
    itemType: ItemType
    subType: String
    province: Region
    vendor: String
    sortOrder: SortOrder
    sortField: FlatSortField
    query: String
    brand: String
  ): ItemFlatListings
}
