# types of ammo.
enum AmmoType {
  centerfire
  rimfire
  shotgun
}
# provinces  (and territories) of canada
enum Province {
  AB
  BC
  MB
  NB
  NF
  NS
  NT
  NU
  ON
  PE
  QC
  SK
  YT
}
# colunm sort order
enum SortOrder {
  ASC
  DES
}
# column to sort on
enum SortField {
  name
  link
  minPrice
  minUnitCost
}

type AmmoListing {
  img: String
  price: Float!
  name: String!
  link: String!
  vendor: String!
  provinces: [Province] #[Province!]!
  calibre: String!
  brand: String!
  count: Float
  unitCost: Float
  ammoType: AmmoType!
}
type AmmoGroup {
  name: String!
  brand: String!
  calibre: String!
  ammoType: AmmoType!
  minPrice: Float!
  maxPrice: Float!
  minUnitCost: Float
  maxUnitCost: Float
  img: String
  vendors: [AmmoListing!]!
}
type AmmoListings {
  page: Int!
  pages: Int!
  pageSize: Int!
  items: [AmmoGroup!]!
}
type Vendor {
  name: String!
  provinces: [Province!]!
  location: String!
  logo: String!
  link: String!
  background: Boolean
}
type BestPrice {
  unitCost: Float!
  calibre: String!
  type: AmmoType #!
}
# The "Query" type is the root of all GraphQL queries.
# (A "Mutation" type will be covered later on.)
type Query {
  vendors(province: Province): [Vendor]
  bestPrices(type: AmmoType, calibres: [String!]): [BestPrice]
  ammoListings(
    page: Int
    pageSize: Int
    ammoType: AmmoType
    calibre: String
    province: Province
    vendor: String
    sortOrder: SortOrder
    sortField: SortField
    query: String
  ): AmmoListings
}
